swagger: "2.0"
info:
  title: "Deposit Calculator API"
  description: "API для вычисления депозита на конец каждого последующего месяца"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
paths:
  /calculate:
    post:
      summary: "Вычисление депозита по вкладу"
      description: "Вычисление депозита по вкладу используя введённые параметры"
      parameters:
        - name: "body"
          in: "body"
          description: "Обязательные поля для вычисления"
          required: true
          schema:
            type: "object"
            properties:
              date:
                type: "string"
                description: "Дата депозита"
                example: "31.01.2021"
                format: '%d.%m.%Y.'
              periods:
                type: "integer"
                description: "Количество месяцев"
                example: 3
                minimum: 1
                maximum: 60
              amount:
                type: "integer"
                description: "Сумма вклада"
                example: 10000
                minimum: 10000
                maximum: 3000000
              rate:
                type: "number"
                format: "float"
                description: "Процентная ставка"
                example: 6.0
                minimum: 1.0
                maximum: 8.0
      responses:
        200:
          description: "Успешный ответ"
          schema:
            type: "object"
            additionalProperties:
              type: "number"
              description: "Сумма вклада на конец месяца"
              example: 10050.0
          examples:
            application/json:
              {
                "31.01.2021": 10050,
                "28.02.2021": 10100.25,
                "31.03.2021": 10150.75
              }
        400:
          description: "Невалидные входные данные"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "date: Некорректный формат даты. Используйте формат %d.%m.%Y."
