name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-root

    - name: Run linters
      run: |
        poetry run black app/
        poetry run isort  app/
        poetry run flake8 app/

    - name: Run tests
      run: |
        poetry run python -m unittest discover -s tests
        poetry run coverage run -m unittest discover -s tests
        poetry run coverage report

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}g