name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: python-poetry/poetry-action@v3
      with:
        poetry-version: '1.8.0'

    - name: Install dependencies
      run: |
        poetry install --no-root

    - name: Run linters and test
      run: |
        make all
